### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by xorith** [demmonic/WurmNoSteamPatcher#1]
Just thought I'd make a comment that by using this patch on a game server, you essentially open yourself up to spoofing attacks by clients that are also patched.

It also would render any patched client useless against servers that are not also patched.

In essence, there is little gain from using this code except to open yourself up to serious security risks.

**Comment by demmonic** [comment]
This is just a smaller piece of the puzzle for a collection of security testing tools. You're 100% correct, but this was never meant to be used on a publicly exposed server. The only reason you would have for doing that is having a cracked server, which I do not condone _at all_.

I hope anyone considering using this is already fully aware of these risks. 

Thank you.
